= Textbook: Data Science I

This repository contains the source materials, as well as the authoring and publishing tools, of the textbook of the University of Chicago course Data Science I.

All textbook contents are generated from Jupyter Notebooks and Markdown files, converted by https://jupyterbook.org/[Jupyter Book] into HTML, and served by GitHub Pages.

The published textbook may be accessed https://ds1.datascience.uchicago.edu/[here].


== Getting started

=== Prerequisites

Development of this textbook requires that you have pre-installed on your computer:

* https://www.python.org/downloads/[Python version 3.6 or higher]
* https://docs.docker.com/install/[Docker-CE]

If you're not sure, you can test for the presence of commands in your terminal as follows:

    $ which docker python3.6 python3.7

=== Set-up

Set up and check your environment for textbook authoring by sourcing the repository's included Bash script:

    $ source setup

The `setup` script will guide you through installation of any further required libraries.

==== Troubleshooting set-up

===== Other shells

If you use a shell other than Bash, you may instead execute the following setup command directly:

    $ ./setup-install

However, this command is unable to affect your active shell; to correct this, you may simply start a new shell.

===== Other situations

Set-up scripting attempts to guide authors in setting up their computers; however, your computer might vary considerably from expectations!

If you have both Docker and Python installed, the only further requirement is to install https://pypi.org/project/argcmdr/[argcmdr].

This may be achieved generally via `pip`, _e.g._:

    $ pip install argcmdr

Then, the `manage` command should be available through your `PATH`:

    $ which manage
    /path/to/manage

`setup` performs the above on your behalf, attempting to correct for environmental variability.

Issues with `setup` and the above instructions may be https://github.com/chicago-cdac/textbook-datascience-1/issues[reported as Issues].


== Authoring content

Having set up your textbook-authoring environment, you may manage it via the installed shell command, `manage`, (executed from the repository's root directory):

    $ manage [--help|...]

To begin a session, you'll want to start the authoring servers:

    $ manage start

The above command will ensure that the necessary Docker containers are built and running.

At the end of the output of the `start` command, you'll see the URL of your local authoring server: a Jupyter server, for authoring plain-text content via Markdown files and programmatic/interative content via Jupyter Notebooks.

Textbook source files reside under the `textbook/` directory. (The Jupyter server opens this directory by default.)

To preview local changes to these files, execute the `build` command:

    $ manage build

The above command will generate HTML from the textbook source files, and write these under the `preview/html/` directory. Your changes will then be available for preview.

[NOTE]
====
HTML files generated for local preview are not intended to be committed to the repository.

(The `.gitignore` file reflects this and these will be ignored by default.)
====

=== Packing it in

Once you've completed your session, feel free to release computational resources by stopping the authoring servers:

    $ manage stop


== Publishing

https://github.com/chicago-cdac/textbook-datascience-1/deployments/activity_log?environment=github-pages[GitHub Pages] serves the textbook's generated HTML at https://ds1.datascience.uchicago.edu/[its configured domain].

The textbook is so published via the https://github.com/chicago-cdac/textbook-datascience-1/actions/workflows/textbook.yml[Github Actions workflow: Textbook] (controlled via link:.github/workflows/textbook.yml[textbook.yml]).

And the workflow is triggered &ndash; and the textbook published &ndash; by the https://github.com/chicago-cdac/textbook-datascience-1/releases[publishing of a new Release].

NOTE: Release tags *must* follow the semantic versioning pattern: `[0-9].[0-9]*`. For example: `0.0.4`.

=== Troubleshooting builds

If GitHub has a problem building what's been committed, it will e-mail the user who authored the failing release.

The progress of the publishing workflow may otherwise be reviewed: https://github.com/chicago-cdac/textbook-datascience-1/actions/workflows/textbook.yml[Github Actions workflow: Textbook].


== Managing the Image

The textbook authoring- and build-environment is provided as https://github.com/chicago-cdac/textbook-datascience-1/pkgs/container/textbook-jupyter-service[a Docker container], the image of which is maintained under directory link:image/[].

Changes to any files under that directory, once pushed to the repository, trigger the rebuild and push of that image, via the https://github.com/chicago-cdac/textbook-datascience-1/actions/workflows/image.yml[Github Actions workflow: Image] (controlled via link:.github/workflows/image.yml[image.yml]).
