= Textbook: Data Science I

This repository contains the source materials, as well as the authoring and publishing tools, of the textbook of the University of Chicago course Data Science I.

All textbook contents are generated from Jupyter Notebooks and Markdown files, converted by https://jupyterbook.org/[Jupyter Book] into HTML, and served by GitHub Pages.

The published textbook may be accessed https://ds1.datascience.uchicago.edu/[here].


== Getting started

=== Prerequisites

Development of this textbook requires that you have pre-installed on your computer:

* https://www.python.org/downloads/[Python version 3.6 or higher]
* https://docs.docker.com/install/[Docker-CE]

If you're not sure, you can test for the presence of commands in your terminal as follows:

    $ which docker python3.6 python3.7

=== Set-up

Set up your environment for textbook authoring by sourcing the repository's included Bash script:

    $ source setup

The `setup` script will guide you through installation of any further required libraries.

[TIP]
====
If you use a shell other than Bash, you may instead execute the following setup command directly:

    ./setup-install

However, this command is unable to affect your active shell; to correct this, you may simply start a new shell.
====


== Authoring content

Having set up your textbook-authoring environment, you may manage it via the installed shell command, `manage`, (executed from the repository's root directory):

    $ manage [--help|...]

To begin a session, you'll want to start the authoring servers:

    $ manage start

The above command will ensure that the necessary Docker containers are built and running.

At the end of the output of the `start` command, you'll see the URL of your local authoring server: a Jupyter server, for authoring plain-text content via Markdown files and programmatic/interative content via Jupyter Notebooks.

Textbook source files reside under the `textbook/` directory. (The Jupyter server opens this directory by default.)

To preview local changes to these files, execute the `build` command:

    $ manage build

The above command will generate HTML from the textbook source files, and write these under the `preview/html/` directory. Your changes will then be available for preview.

[NOTE]
====
HTML files generated for local preview are not intended to be committed to the repository.

(The `.gitignore` file reflects this and these will be ignored by default.)
====

=== Packing it in

Once you've completed your session, feel free to release computational resources by stopping the authoring servers:

    $ manage stop
