# Working with Numeric Data
*Amanda R. Kube Jotte and Evelyn Campbell*

Python offers a number of different data types that can be manipulated and used by various functions. Some important built-in Python data types include **integers**, **floats**, **booleans**, and **strings**. In the first few sections we will explore each data type along with useful operations that we can perform with them. Then, we will discuss how to do more complicated calculations using **functions** and **methods**. First, we will start with the numeric data types: **integers** and **floats**.

## Integers & Floats

Integers and floating-point numbers (floats) are numeric data types that are often used to perform mathematical operations. **Integers** consist of whole numbers, while **floats** consist of whole numbers with decimal places. Floats can hold 15-17 digits following the decimal point and can be used to obtain more accurate calculations. However, it is easier and faster for a computer to do calculations using integers. Thus, one must weigh the pros and cons of using these data types when doing calculations and writing functions to obtain outcomes that are most aligned with their end goals. Let's take a look at these data types in more detail.


In [ ]:
print(4567)
print(45.67)

4567
45.67


Python has built-in **functions** that use values and expressions as an argument, or input, to perform a task and produce an output. A common one is the `print()` function, which displays an output. We will learn about a few more built-in functions that are associated with datatypes in this section. Built-in functions will be further discussed in depth in section [Section 3.5](../../03/5/IntroFunctions.ipynb).

We can confirm the integer and float above by calling the `type()` function on these values.

In [ ]:
type(4567)

int

In [ ]:
type(45.67)

float

These numerical data types can be converted between floats and integers using the `float()` and `int()` functions. Let's see what happens when we convert the integer value 4567 to a float and the float value 45.67 to an integer:

In [ ]:
float(4567)

4567.0

In [ ]:
int(45.67)

45

We can see that the conversion of an integer to a float simply adds one significant figure after the decimal place. Moreover, converting a float to an integer rounds the number *down* to the nearest whole number.

## Operations

To work with numeric data in Python, we need to know the basic mathematical operators. In this section, we will see how to use Python to perform mathematical operations such as addition, subtraction, multiplication, division, and exponentiation.

### Addition and Subtraction

Addition and subtraction are relatively self explanatory in Python. We use the operators `+` and `-` as we would on a calculator. For example, we can type $3 + 4$ in a Jupyter notebook cell and run it to output the solution, 7, as follows:

In [ ]:
3 + 4

7

We can do the same for subtraction, subtracting 6 from 10 to get 4.

In [ ]:
10 - 6

4

We can create longer expressions as well.

In [ ]:
2 + 5 - 4 + 10 + 2

15

### Multiplication and Division

The operator for multiplication in Python is `*`, which we can use as follows.

In [ ]:
3 * 6

18

There are multiple types of division in Python. We can use `/` for normal division which may result in a number with a decimal. For example:

In [ ]:
7 / 2

3.5

We can also do **floor division** using `//`. Floor division is equivalent to dividing and then taking the *floor* of the result (rounding down to the nearest whole number).

In [ ]:
7 // 2

3

We can also use the **modulo** operator `%` to get the remainder after division. Using the same example as above. We know that two goes into 7 three times leaving a remainder of 1. Therefore, 7 modulo 2 gives the result 1.

In [ ]:
7 % 2

1

Let's try another example. 

In [ ]:
13 / 5

2.6

Thirteen divided by five is 2.6. The floor division of Thirteen and five, is 2 as five goes into 13 two times. 

In [ ]:
13 // 5

2

And 13 modulo 5 is 3 as 3 is the remainder.

In [ ]:
13 % 5

3

### Exponentiation

We can also compute exponents using Python. The operator for this is `**`. This is an example of a time where **syntax**, or the arrangement of letters and symbols, is important. Adding a space as in `* *` will not work!

In [ ]:
2 ** 3

8

In [ ]:
2 * * 3

SyntaxError: invalid syntax (<ipython-input-64-0f343c0fc354>, line 1)

The expression 2 * * 3 produces an error as Python does not recognize that you meant `**`.

To take the root of a number in Python, we simply exponentiate by the reciprocal. For example, to take the square root of 4 or the cubed root of 8, we would do the following.

In [ ]:
4 ** (1/2)

2.0

In [ ]:
8 ** (1/3)

2.0

### Order of Operations

Notice that we had to use parentheses above. If we would not have included those parentheses, we would have gotten a different result. For example:

In [ ]:
8 ** 1/3

2.6666666666666665

Python follows the same order of operations that you learned in elementary school. You might remember learning a mnemonic phrase such as 'Please Excuse My Dear Aunt Sally' to remember in what order to execute operations: Parentheses, Exponentiation, Multiplication and Division, Addition and Subtraction. In the previous code cell, Python computed exponentiation first, computing 8 to the first power, then divided by 3. Using parentheses not only avoids this issue, but makes your code easier to read as well! For example, these give the same result, but the second is much more clear.

In [ ]:
5 + 10 ** 2 - 5 // 2 * 4

97

In [ ]:
5 + (10 ** 2) - ((5 // 2) * 4)

97


Below is a table of summarizing the operators we learned in this chapter.

| Operator | Used For       | Example Expression | Result|
|----------|----------------|--------------------|-------|
| +        | Addition       | 5 + 2              | 7     |
| -        | Subtraction    | 5 - 2              | 3     |
| *        | Multiplication | 5 * 2              | 10    |
| /        | Division       | 5 / 2              | 2.5   |
| //       | Floor Division | 5 // 2             | 2     |
| %        | Modulo         | 5 % 2              | 1     |
| **       | Exponentiation | 5 ** 2             | 25    |

Each of these operators can act on numeric data types (integers or floats). In the next sections, we will discuss non-numeric data types and how to work with them in Python.